[workspace]
resolver = "2"
members = [
  "bevy_blob_loader",
  "example",
]

[workspace.package]
version = "0.0.3"
edition = "2021"
repository = "https://github.com/kayhhh/bevy_blob_loader"
license = "MIT OR Apache-2.0"

[profile.dev]
opt-level = 1

[profile.dev.package."*"]
opt-level = 3

[profile.release]
lto = true
opt-level = 'z'
